name: haedal
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-145.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  page_transition: ^2.1.0
  geolocator: ^10.1.0
  flutter_compass: ^0.8.0
  permission_handler: ^11.1.0
  flutter_easyloading: ^3.0.5
  sliding_up_panel: ^2.0.0+1
  flutter_naver_map: ^1.0.2
  flutter_datetime_picker:
    git:
      url: https://github.com/ryojiro/flutter_datetime_picker.git
      ref: 32ea47240c10469ad31db0084f5d9b7a12d16e01
  table_calendar: ^3.0.9
  get: ^4.6.5
  flutter_secure_storage: ^9.0.0
  jwt_decode: ^0.3.1
  json_annotation: ^4.8.1
  dio: ^5.1.2
  fluttertoast: ^8.2.2
  auto_size_text: ^3.0.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.4
  http: ^1.1.0
  iconsax: ^0.0.8
  insta_assets_picker: ^2.2.0
  wechat_camera_picker: ^4.1.1
  kpostal: ^0.5.1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  image_gallery_saver: ^2.0.3
  intl: ^0.18.1
  gap: ^3.0.1
  syncfusion_flutter_calendar: ^23.2.7
  flutter_snake_navigationbar: ^0.6.1
  flutter_riverpod: ^2.4.9
  flutter_spinkit: ^5.2.0
  toggle_switch: ^2.3.0
  kakao_flutter_sdk: ^1.9.2
  flutter_naver_login: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/marker/
    - assets/icons/
    - assets/html/
    - assets/icons/svg/
    - .env

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
